[tool.isort]
force_single_line = true
lines_after_imports = 2
force_sort_within_sections = true
known_first_party = "ddapm_test_agent"
default_section = "THIRDPARTY"
skip = [".riot/", ".venv/", "public_api/"]
line_length = 120
profile = "black"

[tool.black]
line_length = 120
exclude = '''
(
  /(
    \.riot
  | \.venv.*
  | \.eggs
  | public_api
  )/
)
'''
