name: Changelog
on:
  push:
    branches:
      - master
  pull_request:
    # Important that we run on `labeled` and `unlabeled` to pick up `changelog/no-changelog` being added/removed
    # DEV: [opened, reopened, synchronize] is the default
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]
jobs:
  validate:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Include all history and tags
        with:
          fetch-depth: 0

      # Ensure a new reno release note was added in this PR.
      # Use `reno new <slug>` to add a new note to `releasenotes/notes`,
      #   or add `changelog/no-changelog` label if no release note is needed.
      - name: Ensure release note added
        # Only run this on pull requests
        if: github.event_name == 'pull_request'
        run: scripts/check-releasenotes

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install reno docutils

      - name: Lint changelog notes
        run: reno lint
